baseURL = 'https://koolsing.pages.dev'
locale = 'en-us'
title = 'Kuldeep Singh'
theme = 'PaperMod'

[params]
  googleAnalytics = ""
  defaultTheme = "dark"
  disableThemeToggle = true 
  showReadingTime = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  disableSpecialLargeFirstPost = true
  showDescription = true

  # The Header Logo configuration
  [params.label]
    text = "Kuldeep Singh"
    icon = "/blog-icon.png"  # Ensure this file is in your /static folder
    iconHeight = 30
    iconWidth = 30

  # The Browser Tab Icon configuration
  [params.assets]
    favicon = "/blog-icon.png"