baseURL = 'https://koolsing.pages.dev'
locale = 'en-us'
title = 'Kuldeep Singh'
theme = 'ink-free'
paginate = 5

[permalinks]
  posts = "/:year/:month/:title"

[params]
  # Optional 64x64 avatar image.
  #avatar = ""

  featherIconsCDN = false
  mermaidCDN = "https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.esm.min.mjs"

  enableUmami = false

  # Site color - dark/light/auto
  mode = "auto"

  toc = "both"
  enableTocTrunate = true

  maxTags = 7
  wpm = 250

  statisticsEnabled = false

  # The Browser Tab Icon configuration
  [params.assets]
    favicon = "/blog-icon.PNG"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Tags & Stats"
  url = "/tags"
  weight = 3

[[params.social]]
  name = "RSS"
  icon = "rss"
  url = "/index.xml"

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
