baseURL = 'https://koolsing.pages.dev'
locale = 'en-us'
title = 'Kuldeep Singh'
theme = 'PaperMod'

[params]
  googleAnalytics = ""
   defaultTheme = "dark"
   disableThemeToggle = true 
  showReadingTime = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  disableSpecialLargeFirstPost = true
    showDescription = true